version: "2"
services:
  deploy:
    env_file: deploy-dev.env
    environment:
      - FIREBASE_PROJECT=develop
    build:
      context: ./
      dockerfile: deploy.dockerfile
    volumes:
      - ./:/mount
