name: deploy-stage

on:
  push:
    branches:
      # Now, dev branch is treated as stage
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      WYLY_APP_FIREBASE_TOKEN_STAGE: ${{ secrets.FIREBASE_TOKEN_STAGE }}

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/test
      - name: Deploy firebase
        run: |
          docker-compose -f ./deploy-stage-compose.yml build
          docker-compose -f ./deploy-stage-compose.yml run deploy
      - name: Slack Notification
        uses: homoluctus/slatify@master
        if: always()
        with:
          type: ${{ job.status }}
          job_name: "Deploy to Stage Firebase"
          mention: "here"
          mention_if: "failure"
          channel: "#wyly-github"
          icon_emoji: "nyanbo-_firebase"
          url: ${{ secrets.SLACK_WEBHOOK_URL }}
          commit: true
          token: ${{ secrets.GITHUB_TOKEN }}
