name: deploy-dev

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      WYLY_APP_FIREBASE_TOKEN_DEV: ${{ secrets.FIREBASE_TOKEN_DEV }}

    steps:
      - uses: actions/checkout@v1
      - name: Deploy firebase
        run: |
          docker-compose -f ./deploy-dev-compose.yml build
          docker-compose -f ./deploy-dev-compose.yml run deploy
