name: deploy-dev

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN_DEV }}

    steps:
      - uses: actions/checkout@v1
      - name: create env file
        run: echo ${FIREBASE_TOKEN_DEV}>deploy-dev.env
      - name: Deploy firebase
        run: docker-compose -f ./deploy-dev-compose.yml up --build
