name: deploy-dev

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN_DEV }}

    steps:
      - uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "13.x"
      - name: Install firebase-tools
        run: npm install -g firebase-tools
      - name: Install functions dependencies
        run: |
          cd functions
          npm install
      - name: Deploy firebase
        run: |
          firebase use develop --token ${FIREBASE_TOKEN}
          firebase deploy --token ${FIREBASE_TOKEN}
