name: test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SECRET_SAMPLE: ${{ secrets.SECRET_SAMPLE }}

    steps:
      - uses: actions/checkout@v1
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo ${SECRET_SAMPLE}
          echo Add other actions to build,
          echo test, and deploy your project.
